spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeopathy_clinic
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8080

logging:
  level:
    com.homeopathy: DEBUG
    org.springframework.security: DEBUG